version: 2.1

jobs:
  compile:
    docker:
      - image: ubuntu:20.04
    steps:
      - checkout
      - run:
          name: Install arduino-cli
          command: |
            apt update
            apt install -y curl
            curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
            export PATH=/root/project/bin
            arduino-cli core install arduino:avr
            arduino-cli core update-index
      - run:
          name: Install libraries
          command: |
            export PATH=/root/project/bin
            arduino-cli lib install  Adafruit\ NeoPixel@1.10.6
      - run:
          name: compile
          command: |
            export PATH=$PATH:/root/project/bin
            arduino-cli compile -b arduino:avr:nano --output-dir /root/project/compiled arduino-ws2812b-blinker
            cd compiled && ls -la
      - persist_to_workspace:
          root: .
          paths: compiled
  upload-nightly:
    docker:
      - image: ubuntu:20.04
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: get new version
          command: |
            apt update
            apt install -y curl
            export NEW_VERSION=$( \
            curl -L https://github.com/MerzSebastian/arduino-ws2812b-blinker/releases/latest | \
            grep -oP '(?<=releases/tag/).*?(?=" />)' | \
            head -1 | \
            awk -F. -v OFS=. '{$2 += 1 ; print}')

            
workflows:
  compile:
    jobs:
      - compile
      - upload-nightly:
          requires:
            - compile
