version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run:
          name: Install avr toolchain
          command: |
            apt update
            apt install -y gcc-avr avr-libc avrdude curl git
            git clone https://github.com/arduino/ArduinoCore-avr.git
      - run:
          name: compile for atmega328p
          command: >
            avr-g++ -mmcu=atmega328p -DARDUINO=105 -DF_CPU=16000000L -Os
            -x c++ -include ArduinoCore-avr/cores/arduino/Arduino.h
            arduino-ws2812b-blinker/arduino-ws2812b-blinker.ino


workflows:
  build:
    jobs:
      - build
