version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run:
          name: Install avr toolchain
          command: apt install gcc-avr avr-libc avrdude


workflows:
  build:
    jobs:
      - build
