version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run:
          name: Install avr toolchain
          command: |
            apt update
            apt install -y gcc-avr avr-libc avrdude curl git
            git clone https://github.com/arduino/ArduinoCore-avr.git
      - run:
          name: install Adafruite NeoPixel library
          command: |
            cd ArduinoCore-avr/libraries
            git clone https://github.com/adafruit/Adafruit_NeoPixel.git
      - run:
          name: compile for atmega328p
          command: >
            avr-g++ -mmcu=atmega328p -DARDUINO=105 -DF_CPU=16000000L -Os -x c++ 
            -I ArduinoCore-avr/cores/arduino/ 
            -I ArduinoCore-avr/variants/standard/ 
            -I ArduinoCore-avr/libraries/Adafruit_NeoPixel/ 
            -I ArduinoCore-avr/libraries/EEPROM/src/ 
            arduino-ws2812b-blinker/arduino-ws2812b-blinker.ino
  cli-build:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run:
          name: Install avr toolchain
          command: |
            apt update
            apt install -y curl
            curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
            arduino-cli core update-index
      - run:
          name: compile
          command: |
            arduino-cli compile -b arduino:avr:nano /


workflows:
  build:
    jobs:
      - build
      - cli-build
